### ISSUE TITLE
Support for koa2 / Untraced mysql query

### ISSUE THREAD

**Issue by 1602** [GoogleCloudPlatform/cloud-trace-nodejs#326] opened 2016-12-04 17:07 UTC
I've noticed that this library supports koa (btw, for some reason readme didn't mention it). My app is running on koa v2, so, i've patched this library a little: https://github.com/1602/cloud-trace-nodejs/commit/b809244b72c64a63c8a13587cff1dc180d3b2d8a

Not sure if I could submit PR adding koa v2 support.

And another question, possibly unrelated one. In app i'm tracing I use mysql and knex odm, and I see no traces of db calls, connected to root span registered by koa middleware, in debug log i see 

```
DEBUG:@google/cloud-trace: Untraced mysql query: { sql: ...
```

Any suggestions on how to make it working would be very welcome. Thanks!

**Comment by matthewloring** [comment] 2016-12-04 21:40
The readme does not mention koa because it is not a framework we officially support and keep up to date. We welcome pull requests and are happy to accept changes to support koa v2. I see that your koa patch uses async functions which I assume requires transpilation. We do not currently have a transpilation workflow for this project so adding tests for the koa v2 patch may require some more machinery.

The problems with mysql tracing are likely caused by interference from the generic-pool module which is used by knex instead of the builtin connection pooling in the mysql module. If this is the case, we will need to instrument the generic-pool module to make sure mysql requests can be attached to the appropriate koa spans. We can take a look at knex and verify that this is actually the issue you are observing.

**Comment by 1602** [comment] 2016-12-05 11:24
re: koa2 support, thanks it is clear, I will rewrite to pure promises and submit PR

re: mysql, sounds like this is it, i can not confirm, because it seems like it is not possible to not use generic pool in knex. it would be very nice if you help to explore generic-pool issue, i'm totally lost in cls stuff.

**Comment by ofrobots** [comment] 2016-12-05 15:25
I've opened #327 to track the enhancement request for preserving context across knex. Closing this issue.

**Closed by ofrobots** 2016-12-05 15:25 UTC
Labels: enhancement
