### ISSUE TITLE
Performance Problem

### ISSUE THREAD

**Issue by SimonSun1988** [GoogleCloudPlatform/cloud-trace-nodejs#544] opened 2017-08-26 16:00 UTC
I use trace engine in my api server, but I found it increase CPU and memory usage.

Any suggestions or I have to adjust my config.

```js
require('@google-cloud/trace-agent').start({
    projectId: projectId,
    keyFilename: keyFilename,
    logLevel: 1,
    samplingRate: 1000
});
```

**Comment by matthewloring** [comment] 2017-08-26 20:36
Do you have any specific information on how much CPU and memory usage increased with the trace agent? From the config, it looks like you're sampling 1000 requests a second which can generate a lot of information quickly. The CPU and memory impact will be lower if you decrease the sampling rate. I believe the default of 10 is usually sufficient unless you are trying to observe a particularly rare event.

**Comment by ofrobots** [comment] 2017-09-01 17:38
@SimonSun1988 Please try with the default sampling rate. An aggressive sampling rate of 1000 is probably the cause of increased memory and cpu usage.

**Comment by SimonSun1988** [comment] 2017-09-04 01:39
thanks, I will try it.

**Comment by ofrobots** [comment] 2017-11-14 22:22
I am closing this issue, as I believe it has been addressed. Please add a comment if this is still and issue.

**Closed by ofrobots** 2017-11-14 22:22 UTC
