### ISSUE TITLE
Can traces be added to normal node.js functions

### ISSUE THREAD

**Issue by grandmore** [GoogleCloudPlatform/cloud-trace-nodejs#289] opened 2016-08-05 14:12 UTC
I want to add a simple set of traces around some of my node,js function but currently the span function only support certain frameworks. The Custom Tracing API says it only supports `express`, `hapi` &  `restify`.

Can we use the span classes outside of these frameworks in normal node code to do tracing. 

Can this be done with normal node functions ?

For example

```
var agent = require('@google/cloud-trace').start();
var span = agent.startSpan('name', {label: 'value'});

function f1( 'service1:f1', function (args, callback) {
    f2( null, function (err, callback) {
        return callback(null data)
    }
});

function f2( 'service1:f2', function (args, callback) {
    return callback(null, {'data'} )
});

// start trace
var span = agent.startSpan('name', {label: 'f1-f2 trace'});

// run function
f1( 'data', function (err, callback) {

    //end trace
    agent.endSpan(span, {label2: ''f1-f2 trace'});
}
```

Thanks

**Comment by matthewloring** [comment] 2016-08-05 16:29
We do not currently support generating spans outside of the web frameworks you mentioned above. This is something we may be able to support in the future but I want to understand the use case. Are you building a service using a different web framework or trying to trace Node.js in a different context?

**Comment by grandmore** [comment] 2016-08-05 16:38
I'm not using any of these frameworks. I use a mix of different technologies depending on the use case.

For example relay/react, straight node, golang etc.

I have micro-service architecture and the services are written in different languages and different technology  to watch their use. All of them are wrapped in docker and most don't use frameworks at all, there far to large for whats needed.

Thanks. for the fast reply.

**Comment by matthewloring** [comment] 2016-08-05 17:24
I am specifically interested in how the Node services handle web traffic. When you say straight node/no framework, does this mean serving requests with the Node.js http module, plain sockets, or something else? 

For relay/react, we should be able to trace things like react server side rendering or a relay database with custom spans as long as the work is being done within a supported web framework.

**Comment by grandmore** [comment] 2016-08-05 17:31
Primarily each service communicates over http when the services are in separate docker containers. Some of the services communicate internally, even through they are structured as micro-services. This is to avoid 'always' communicating over a network, when internal communication is 100x faster.

I'm intending changing http to grcp later.

I'm interested in tracing both of these scenarios. I can use zipkin and like, but I was curious about google trace app to see if it can do similar tracing.

**Comment by matthewloring** [comment] 2016-08-05 19:03
I am curious what prompted the use of plain http as opposed to one of the other frameworks. Was this a system requirement, personal preference, or something else?

**Comment by grandmore** [comment] 2016-08-05 19:11
The Frameworks are fine, and I have used them before, but these are not 'front-end' services/tasks but backend ones. 

I can easily use Restify or Hapi for example, but I can write 100 lines of node code that created these services and never need any framework code, as Node provides everything I need. 

In Golang for example, the standard library does everything I need so there is no need to add the bloat of a framework. It also makes coding / bugging trivial as there is no need to learn how a framework woks to complete the service.

**Comment by ofrobots** [comment] 2016-08-09 00:13
At the moment we only support tracing HTTP servers through frameworks. Supporting bare Node.js HTTP server is something we can look into in the future but have no immediate plans (pull requests are welcome though).

We do plan to implement tracing for gRPC servers in the near/medium-term future.

**Comment by matthewloring** [comment] 2016-09-06 17:45
I'm going to close this for now. Feel free to reopen if you have any additional questions.

**Comment by zbjornson** [comment] 2016-09-12 01:20
I'm also interested in the ability to make traces/spans outside of a framework (although I might be able to work around this limitation). My use case is making custom traces for periodic tasks and other event-driven activities that aren't necessarily spawned by a request.

This seems like a very simple thing to support considering the nature of the trace API -- is it difficult because this library is built around cjs? If I can't come up with a workaround, would you accept a PR for vanilla JS tracing?

**Comment by matthewloring** [comment] 2016-09-12 19:06
@zbjornson It is not difficult and should possible by exposing the existing logic for creating root spans on the public API. We were going to use an api of the form:

```javascript
var span = agent.startRootSpan('name', {label: 'value'});
agent.endSpan(span, {label: 'value'});
```

Despite the similarity with the existing custom span API, we wanted to keep this separate as we did not want people to accidentally create root spans from inside a web framework.

Would the API above satisfy your use case?

We are planning to support this soon but if you would like to put together a PR we are always happy to help with review!

**Comment by zbjornson** [comment] 2016-09-12 19:45
@matthewloring That makes sense to ensure root spans aren't accidentally created.

I only just started using this lib and am working on some other issues first, but I'll work on that if you guys don't get to it before then. Thanks! -- Should this issue be re-opened or a new issue created for tracking maybe?

**Comment by matthewloring** [comment] 2016-09-12 22:04
Sounds good, we can track this here and I can update this once we start work.

**Comment by zbjornson** [comment] 2016-09-13 02:32
Took a stab at this to see if it was a viable solution for #297, but it got more complicated.

Did you guys envision that custom root spans would be used by hooks? e.g. if you made a custom root span in a plain function and had a mongodb call in it, would there be a mongodb span on that custom root span? For what I proposed as a solution in #297 it would be critical that the hooks do not bind to the custom spans. However, that means `startSpan` needs to know which rootSpan (custom or system) to descend from. Doing this with (what I think is) a more typical JS API than continuations would be straightforward:

```js
var agent = require("@google/cloud-trace").start();
function myfn() {
  var trace = agent.startTrace();
  var rootSpan = trace.startSpan(); // w/ above, equivalent to agent.startRootSpan();
  var childSpan = rootSpan.startSpan(); // explicit what to descend from
    // do some kind of work
  childSpan.end();
  var childSpan2 = rootSpan.startSpan();
    // do another kind of work
    var childSpan3 = childSpan2.startSpan(); // nested
  ...
}
```

Note that the above API also provides a mechanism for nesting spans, which isn't available in this lib currently.

Tempted to make a separate, small library for manual tracing that provides that API (maybe gcloud-node would want it, or maybe it could come from refactoring this library into an instrumentation module built on top of a tracing core module) but interested to hear your thoughts first.

**Comment by matthewloring** [comment] 2016-09-13 19:49
The trace agent and service in general are designed with the idea that there is one root span representing asynchronous work at a time. Which root span is in effect is determined when some top level event (user request, cron job, etc) occurs and is propagated across all asynchronous hops originating from that event. Introducing multiple root spans for a particular continuation chain and adding additional logic to decide which is relevant does not align with this design point.

I am hesitant to add a new span type that does not allow the other hooks to attach child spans for this reason. One alternative would be coming up with a mechanism to filter out spans according to user provided rules (either as they are created or in the UI).

Nesting is currently handled in the UI based on start and end times as opposed to explicit parent/child relationships in the trace graph. As long as nested spans are correctly associated with the same root span, their nesting structure can be inferred and displayed correctly.

I am happy to discuss modifications to our existing api, I just want to make sure we are not introducing additional complexity or unnecessary margin for error.

**Comment by zbjornson** [comment] 2016-09-14 20:00
Agreed that the current design with a single root span makes sense, and some "child-free" span type would add complication to the API.

That is, however, I think the simplest and lowest-overhead long-term solution to #297 (giant traces). I made up an example [simple tracing library](https://github.com/zbjornson/gcloud-trace) yesterday built on top of google-cloud/common for this purpose. Its API is basically the same as the custom API in this module -- what I was describing earlier as what a "core tracing module" could look like, and which could be built on top of by an instrumentation library like this. (If you're interested in that approach, happy to keep talking and propose the lib as a submission to gcloud-node.)

**Comment by matthewloring** [comment] 2016-09-15 16:55
Cool! I can take a look at the library in more detail later. Just looking through the example in the `README`, I am not seeing any differences in what can be expressed between your API and the api of this module (with the addition of custom root spans). Is the intent that no child spans automatically generated by hooks would attach to these custom spans?

We have talked about in the past (https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/40) about moving our hooks into a separate module as you suggest. This would allow people to bring in only the ones they need and simplify the process for adding new hooks. The barrier was setting up a clean interface to allow hooks to instrument modules at load time. The express hook in your example is written as a middleware that does not require modification to the express module itself. Many of our other hooks require monkey patching objects inside mongodb, mysql and others before any user code can observe them. We could reinvestigate the feasibility of exposing a load-time instrumentation api on this module if the benefits are strong enough.

**Comment by zbjornson** [comment] 2016-09-15 19:24
Indeed, my lib could mostly be replaced when custom root spans are allowed. The big one is no child spans from hooks, yes, but it's also appealing because it doesn't do any patching or use CLS. Some other differences, many of which have workarounds and are minor, and all of which would be easy to add to this lib if desired:

* `tracing.getTrace(traceId, cb)` that e.g. allows a trace started on the RPC client to be continued from the RPC server. Depending on what's exposed, might be possible with this lib once custom root spans are added -- as long as you have the traceId, know a unique spanId to use next and can set those values, you don't need this.
* `span.cancel()`. Example use cases:
  * In a tryFromCache-fallbackToOriginFetch scenario, I use this to trace cache hits and not misses. (Our hits are still expensive and misses are ~free.)
  * In a race scenario ([ex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race), [ex](http://caolan.github.io/async/docs.html#.race)), only trace the winner. (e.g. tryFromCache and originFetch simultaneously, or try two different servers for the same resource.)
* `trace.cancel()`. Example use cases:
  * Declare within a route handler (instead of in the config) which express routes not to trace.
  * Conditionally don't trace a route.
* `span.startSpan()` to create nested spans. Only useful if you're using a viewer other than GCP's where nested spans are displayed as such. (You commented that nesting can be inferred -- if I understand, yes, to an extent -- you can order them properly but can't collapse parent spans, color-code them or do more of a flame-graph type of view.)

As for using this lib for strictly manual tracing once custom root spans are added, if it's not split into two modules, it would be nice if you didn't have to explicitly disable all of the hooks (and pay attention to what hooks are added as the lib is upgraded to disable those also).

**Comment by matthewloring** [comment] 2016-09-16 14:44
That makes sense. Our library was designed so that users would not have to modify existing code in order to get tracing of common frameworks (with the option to add custom spans if desired). If someone wants more fine grained control over all spans at the cost of modifying their code base to pass the spans around and manually trace all events of interest I think a library like yours sounds like the right move. We could investigate a completely unpatched manual mode in the future but it is not on our short-term roadmap.

**Comment by matthewloring** [comment] 2016-10-04 03:01
Today's release of the trace agent includes support for custom root spans. Take a look and let me know if it will work for your custom span needs.

**Comment by matthewloring** [comment] 2016-10-07 17:18
Closing this for now since custom root spans have been published. Feel free to re-open if there are additional questions.

**Closed by matthewloring** 2016-10-07 17:18 UTC
